DEF wTileMap EQU $c3a0
DEF wListScrollOffset EQU $cc36
DEF wInGameTradeGiveMonSpecies EQU $cd0f
DEF wInGameTradeReceiveMonSpecies EQU $cd25
DEF wWhichTrade EQU $cd3d
DEF wCurPartySpecies EQU $cf78
DEF wWhichPokemon EQU $cf79
DEF wLinkState EQU $d0f0
DEF wPartyCount EQU $d123
DEF wPartySpecies EQU $d124
DEF wPokedexOwned EQU $d27b
DEF wPokedexOwnedEnd EQU $d28e
DEF wPokedexSeenEnd EQU $d2a1
DEF wNumBagItems EQU $d2a1
DEF HS_CELADON_MANSION_EEVEE_GIFT EQU $d52d
DEF wPlayerStarter EQU $d696
DEF wCompletedInGameTradeFlags EQU $d6b6
