DEF wTileMap EQU $c3a0
DEF wListScrollOffset EQU $cc36
DEF wCurPartySpecies EQU $cf78
DEF wWhichPokemon EQU $cf79
DEF Initial EQU $d000
DEF wPartyCount EQU $d123
DEF wPartySpecies EQU $d124
DEF wNumBagItems EQU $d2a1
DEF HS_CELADON_MANSION_EEVEE_GIFT EQU $d52d
DEF wPlayerStarter EQU $d696
